### ISSUE TITLE
[BUG] - Improvement in the visibility of text for better visual in dark mode

### ISSUE THREAD

**Issue by Neeraj00121** [supriya46788/Research-Paper-Organizer#400]
## 🐞 Bug Description
In dark mode the text is barely visible in low lighting  .

---

## 📋 Steps to Reproduce
1. Go to Homepage.
2. Enable dark mode.
3. Scroll down to "everything you need for research management  ."
4. Text is not clearly visible .

---

## 🎯 Expected Behavior
Text should appear in clear white colors for better visuals .

---

## 📸 Screenshots

in dark mode (text should appear in white)
<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/fd5837a3-3b20-4591-9605-caff67a38a57" />

in light mode (correctly appearing)
<img width="1919" height="1017" alt="Image" src="https://github.com/user-attachments/assets/c3137ef4-b597-42c7-955b-8d17cf4c3066" />

---

## 💻 Environment
- OS: [e.g. Windows 11, Ubuntu 22.04]
- Browser: [e.g. Chrome 119, Firefox 120]
- Version: [e.g. v1.0.0]

---

**Comment by supriya46788** [comment]
@Neeraj00121 i have merged your pr

**Comment by Neeraj00121** [comment]
Hi @ supriya46788, you have closed this bug but you didn't assign it to me and it havn't  fixed. what you have merged it was my previous pr which was not assigned to me. Please reopen it and assign it to me i will fix this bug.  

Bug is still there
<img width="1918" height="1078" alt="Image" src="https://github.com/user-attachments/assets/b87db4ec-dfbd-4fb1-aaa0-920193a3677c" />
